# Dockerfile has been added in all micro-services, you need to dockerize all micro-services and add docker-compose.yml file
version: '2'
services:
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    network_mode: host
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_HOST: localhost
      MYSQL_DATABASE: userDb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    network_mode: host
    environment:
      MONGO_USERNAME: 
      MONGO_PASSWORD: 
      MONGO_DATABASE: categoryDB
      MONGO_PORT: 27017
      MONGO_HOST: localhost
      
  UserAuthentication-service-app:
    image: userauthenticationervice
    build: Backend/UserAuthentication-Service
    restart: always
    network_mode: host
    depends_on:
      - mysql
    ports:
      - 8089:8089
    expose:
      - 8089
  
  CategoryService-service-app:
    image: categoryservice
    build: Backend/CategoryService/
    restart: always
    network_mode: host
    depends_on:
      - mongo
    ports:
      - 8083:8083
    expose:
      - 8083
      
  NoteService-service-app:
    image: noteservice
    build: Backend/NoteService/
    restart: always
    network_mode: host
    depends_on:
      - mongo
    ports:
      - 8082:8082
    expose:
      - 8082
      
  ReminderService-service-app:
    image: reminderservice
    build: Backend/ReminderService/
    restart: always
    network_mode: host
    depends_on:
      - mongo
    ports:
      - 8081:8081
    expose:
      - 8081
      
  keepnote-frontend:
    image: keepnote-frontend
    build: Frontend/
    ports: 
      - 4200:4200
    expose:
      - 4200